apiVersion: apps/v1
kind: Deployment
metadata:
  name: rice-api-app
  namespace: rice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rice-api-app
  template:
    metadata:
      labels:
        app: rice-api-app
    spec:
      containers:
      - name: rice-api-app
        image: mmregistry.mmvietnam.com:5000/rice-api:v1.0.2-14
        env:
        - name: SUBNET
          value: "10.244.30,172.26.17,172.17.0.1,127.0.0,172.20.240,172.26.16,172.26.24,172.26.130,::1"
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: mmregistry-secret
