apiVersion: v1
kind: Service
metadata:
  name: rice-api-services
  namespace: rice-api  # namespace the same deployement
spec:
  selector:
    app: rice-api-app  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 3001           # Port extenal
      targetPort: 3001    # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
